<a href="https://colab.research.google.com/github/pranita2113/EE_machine_learning/blob/main/task2_EE514.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
import pandas as pd
df = pd.read_csv('/content/RSS - Original.csv')

In [ ]:
df.head()

   X  Y  RSS - A  RSS - B  RSS - C
0  6  2       37       58       68
1  2  2       47       63       73
2  2  6       51       54       73
3  5  6       53       52       74
4  5  9       62       52       65

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   X        24 non-null     int64
 1   Y        24 non-null     int64
 2   RSS - A  24 non-null     int64
 3   RSS - B  24 non-null     int64
 4   RSS - C  24 non-null     int64
dtypes: int64(5)
memory usage: 1.1 KB

In [ ]:
df.describe()

               X          Y    RSS - A    RSS - B    RSS - C
count  24.000000  24.000000  24.000000  24.000000  24.000000
mean    3.416667  18.541667  61.666667  61.375000  58.916667
std     2.041241   9.055285   9.581080   7.400426   9.357242
min     0.000000   2.000000  37.000000  39.000000  45.000000
25%     1.750000  11.250000  58.000000  58.000000  50.000000
50%     3.500000  20.000000  62.000000  62.500000  57.500000
75%     5.000000  25.250000  65.750000  66.000000  66.500000
max     6.000000  30.000000  82.000000  73.000000  74.000000

In [ ]:
df.isnull().sum()

X          0
Y          0
RSS - A    0
RSS - B    0
RSS - C    0
dtype: int64

In [ ]:
print("Missing values before any processing:")
print(df.isnull().sum())
df.dropna()

Missing values before any processing:
X          0
Y          0
RSS - A    0
RSS - B    0
RSS - C    0
dtype: int64

    X   Y  RSS - A  RSS - B  RSS - C
0   6   2       37       58       68
1   2   2       47       63       73
2   2   6       51       54       73
3   5   6       53       52       74
4   5   9       62       52       65
5   1   9       61       61       59
6   5  12       55       39       74
7   3  15       65       55       50
8   6  16       54       58       60
9   4  17       61       72       68
10  4  20       63       58       53
11  6  20       60       62       64
12  0  20       82       69       57
13  1  23       73       64       49
14  4  23       62       66       45
15  6  23       68       67       54
16  6  25       63       62       49
17  3  25       62       62       50
18  1  26       73       66       66
19  1  28       72       67       58
20  3  28       59       66       50
21  5  30       61       64       48
22  3  30       62       63       51
23  0  30       74       73       56

In [ ]:
print(df.shape)
print(df.columns)

(24, 5)
Index(['X', 'Y', 'RSS - A', 'RSS - B', 'RSS - C'], dtype='object')

In [ ]:
X = df [['X','Y']]
y = df ['RSS - A']
# Or use other available columns from df for X and y, such as:
#X = df[['RSS - A','RSS - B','RSS - C']]
#v = df['Y']
from sklearn.model_selection import train_test_split
X_train, X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [ ]:
y_pred=model.predict(X_test)

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)

print("Mean Absolute Error:", mae)
print("Mean Squared Error:",mse)
print("R2 Score:",r2)

Mean Absolute Error: 4.181870948880965
Mean Squared Error: 31.89909390345751
R2 Score: 0.7751050909231705